# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MM - Custom Items Wiki
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  All the things you need to know to make your blocks using CustomItems
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://customitems.otho.me" # the base hostname & protocol for your site
url: "http://localhost:4000/" # the base hostname & protocol for your site
twitter_username: _0tho
github_username:  0tho

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed